### ISSUE TITLE
Missing Commits

### ISSUE THREAD

**Issue by jtbryan** [lining-nwpu/JiTReliability#1]
Hello,

While conducting a study using this dataset, I ran into an issue. Namely, the last 4 datasets in this repository (i.e. POI, Pig, VELOCITY, and XERCESC) seem to have missing commits. For our study, we looked specifically at the ``[PROJECT_NAME]_mapping.csv`` files. When looking at what developer had contributed these defect introducing or defect fixing commits, however, there was a large amount, if not all, of the commits that returned the error ``This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`` when searching for them in the repository. This of course makes it difficult to determine programmatically the history of each commit if it does not exist. I am not sure if this is something I may simply be overlooking, but I simply wanted to bring it to your attention for anyone who may use this dataset in this future.

**Comment by lining-nwpu** [comment]
Hi, 

Thanks for your attention to our dataset.  We got these repositories from  github or jira directly.  Missing Commits you mentioned could be caused by branch_name changed or some other reasons, please see https://stackoverflow.com/questions/50010761/why-do-some-commits-belong-to-no-branch.  And if you want to check what developers had contributed these defect introducing or defect fixing commits, you might use commit hashID (in [PROJECT_NAME]_mapping.csv files) directly to get the info, such as https://github.com/apache/velocity-engine/tree/60b9b9082872a9dfa57a24c2872da63547a727df.  And we used SZZ (https://github.com/wogscpar/SZZUnleashed) to get these dataset (we fixed some problems based downloaded version) and we will add the introducation to our readme file. Hope it could work for your research.

**Comment by lining-nwpu** [comment]
No missing commits, just these commit could not connect with branch for some reason.
